aldenchappell/Eclipse_Rapture

- Config/DefaultEngine.ini
- Eclipse_Rapture.uproject
Enabled required plugins for meta human assets to be used
> enabled meta human plugins

- Content/Blueprints/Characters/Player/BP_EclipseRaptureCharacter.uasset
- Content/Blueprints/Characters/Player/BP_PlayerMain.uasset
- Source/Eclipse_Rapture/Private/Character/EclipseRaptureCharacter.cpp
- Source/Eclipse_Rapture/Public/Character/EclipseRaptureCharacter.h
Much better looking animations, camera orientation, and spine rotation
> Much better looking animations, camera orientation, and spine rotation

- Source/Eclipse_Rapture/Private/Character/EclipseRaptureCharacter.cpp
- Source/Eclipse_Rapture/Public/Character/EclipseRaptureCharacter.h
Moved all C++ Look input code to blueprints
> Comments for look input

- Source/Eclipse_Rapture/Private/Weapons/WeaponBase.cpp
- Source/Eclipse_Rapture/Public/Items/WeaponPickup.h
- Source/Eclipse_Rapture/Public/Weapons/WeaponBase.h
Remade weapon base class, switched inheritance from Item to USkeletalMeshComponent
> Weapon base class

- Content/Art/3DModels/Weapons/Meshes/SM_AssaultRifleBBlack.uasset
- Content/Art/Animation/AnimStarterPack/Showcase.umap
- Content/Art/Animation/Ettore/Pistol/Idle_Pistol.uasset
- Content/Art/MetaHumans/Common/Female/Medium/NormalWeight/Body/metahuman_base_skel.uasset
- Content/Art/MetaHumans/Ettore/Male/Medium/NormalWeight/Body/m_med_nrw_body.uasset
- Content/Blueprints/Characters/Player/ABP_EclipseRaptureCharacter.uasset
- Content/Blueprints/Characters/Player/BP_PlayerMain.uasset
- Content/Blueprints/Items/Weapons/Pickups/BP_AssaultRiflesB_Pickup.uasset
- Content/Blueprints/Items/Weapons/Pickups/BP_PistolAPickup.uasset
- Content/Blueprints/Items/Weapons/Pickups/BP_PistolA_Pickup.uasset
- Content/Blueprints/Items/Weapons/Pickups/BP_WeaponPickup.uasset
- Content/Blueprints/Items/Weapons/Weapons/BP_AssaultRifles_B.uasset
- Content/Blueprints/Items/Weapons/Weapons/BP_Pistols_A.uasset
- Content/Levels/AldenTest.umap
- Source/Eclipse_Rapture/Private/Character/EclipseRaptureCharacter.cpp
- Source/Eclipse_Rapture/Private/Items/WeaponPickup.cpp
- Source/Eclipse_Rapture/Public/Character/EclipseRaptureCharacter.h
- Source/Eclipse_Rapture/Public/Items/WeaponPickup.h
Push before remaking weapon base class
> Remaking weapon base class

- Content/Blueprints/Characters/Player/BP_PlayerMain.uasset
- Content/Blueprints/Items/Weapons/Pickups/BP_AssaultRiflesB_Pickup.uasset
- Content/Blueprints/Items/Weapons/Pickups/BP_PistolA_Pickup.uasset
- Content/Blueprints/Items/Weapons/Weapons/BP_AssaultRifles_B.uasset
- Content/Blueprints/Items/Weapons/Weapons/BP_Pistols_A.uasset
- Content/Levels/AldenTest.umap
- Source/Eclipse_Rapture/Private/Character/EclipseRaptureCharacter.cpp
- Source/Eclipse_Rapture/Private/Weapons/WeaponBase.cpp
- Source/Eclipse_Rapture/Public/Character/EclipseRaptureCharacter.h
- Source/Eclipse_Rapture/Public/Items/WeaponPickup.h
- Source/Eclipse_Rapture/Public/Weapons/WeaponBase.h
Player can now pickup and hold weapons (currently only a pistol and an assault rifle).
> Player can now pickup and hold weapons

- Config/DefaultEngine.ini
- Content/Art/3DModels/Weapons/MilitaryWeapSilver/Weapons/Pistols_A.uasset
- Content/Art/3DModels/Weapons/MilitaryWeapSilver/Weapons/Pistols_A_Skeleton.uasset
- Content/Art/Animation/Ettore/Pistol/AS_TestPistolAim.uasset
- Content/Art/Animation/Ettore/Pistol/BS_PistolAiming.uasset
- Content/Art/Animation/Ettore/Pistol/LS_TestPistolAim.uasset
- Content/Art/MetaHumans/Common/Female/Medium/NormalWeight/Body/metahuman_base_skel.uasset
- Content/Art/MetaHumans/Ettore/Male/Medium/NormalWeight/Body/m_med_nrw_body.uasset
- Content/Blueprints/Items/Weapons/Weapons/BP_Pistols_A.uasset
- Content/Blueprints/Items/Weapons/Weapons/BP_WeaponBase.uasset
- Content/Levels/AldenTest.umap
- Source/Eclipse_Rapture/Private/Weapons/WeaponBase.cpp
- Source/Eclipse_Rapture/Public/Weapons/WeaponBase.h
Fixed aiming animation, player can now ADS with pistol
> Animations update, edit to aiming animation

- Content/Blueprints/Characters/Player/ABP_EclipseRaptureCharacter.uasset
- Content/Blueprints/Characters/Player/BP_EclipseRaptureCharacter.uasset
- Content/Blueprints/Characters/Player/BP_PlayerMain.uasset
- Content/Levels/House.umap
- Content/Levels/MainLevel.umap
- Source/Eclipse_Rapture/Private/Character/EclipseRaptureCharacter.cpp
- Source/Eclipse_Rapture/Public/WeaponTypes.h
- Source/Eclipse_Rapture/Public/Weapons/WeaponBase.h
more updates to come, - need to fix correct buttons swapping to the correct weapon
> Update on weapon swapping

- Content/Levels/House.ini
- Content/Levels/House.umap
- Content/Levels/House/House.umap
- Content/Levels/House/House_HLODLayer_Instanced.uasset
- Content/Levels/House/House_HLODLayer_Merged.uasset
- Content/Levels/House/House_WP.umap
- Content/__ExternalActors__/Levels/House/House_WP/1/AJ/0T5O89VD98NYXKELNNTVWN.uasset
- Content/__ExternalActors__/Levels/House/House_WP/2/X4/YN1JNXFGV94KDWL9IMTADG.uasset
- Content/__ExternalActors__/Levels/House/House_WP/3/27/LUNL2IPYIUDVJF4PPVRN7L.uasset
- Content/__ExternalActors__/Levels/House/House_WP/3/3M/PNIUIFR1UPW6KNC15PW2GG.uasset
- Content/__ExternalActors__/Levels/House/House_WP/3/7B/NPQ2M6VJ532QGLATUVNCO4.uasset
- Content/__ExternalActors__/Levels/House/House_WP/4/6K/T3VE03N9F97KRZ6D22SW8I.uasset
- Content/__ExternalActors__/Levels/House/House_WP/5/98/80OFA3U6OS4VZLPADUZMKV.uasset
- Content/__ExternalActors__/Levels/House/House_WP/5/HJ/EA3AW1IVB3VQURZ7R98ODH.uasset
- Content/__ExternalActors__/Levels/House/House_WP/6/7R/F2EOCUZE3SIRMZX0UIICSI.uasset
- Content/__ExternalActors__/Levels/House/House_WP/6/KC/P41DJPP1Q5PYPT08NCFI0V.uasset
- Content/__ExternalActors__/Levels/House/House_WP/6/MK/I5II6FANMBFR35CFQRWFFY.uasset
- Content/__ExternalActors__/Levels/House/House_WP/7/0M/PC0TZ61FLAZ2VDNMLQM9D0.uasset
- Content/__ExternalActors__/Levels/House/House_WP/9/5Z/0ATNG6ZX6R4PWGR9FZOLPL.uasset
- Content/__ExternalActors__/Levels/House/House_WP/A/5B/CR1TCYHT9LSQ65EO9JY0TO.uasset
- Content/__ExternalActors__/Levels/House/House_WP/A/AO/P88A5YYJ5BVQHYPEGWBFDR.uasset
- Content/__ExternalActors__/Levels/House/House_WP/A/DW/HP08XXHAAWRZSKDCQPGPSH.uasset
- Content/__ExternalActors__/Levels/House/House_WP/B/4D/G03LEKF4KE5ZMXYD67KKQD.uasset
- Content/__ExternalActors__/Levels/House/House_WP/B/KW/P8O00APYDJ2AQ36FAECT9J.uasset
- Content/__ExternalActors__/Levels/House/House_WP/D/FZ/V0RAXMOFRQSV0BF0BSL03K.uasset
- Content/__ExternalActors__/Levels/House/House_WP/E/2F/6OD1RFSDZ8JAZ4FRHK04QA.uasset
- Content/__ExternalActors__/Levels/House/House_WP/E/O5/BDRQQ4TIISU7RZW1JBHYR4.uasset
Created house level, converted to partition.
> House level created

- Content/Art/2DArt/Materials/EnvironmentMaterials/MI_HouseLevelFog.uasset
- Content/Blueprints/Characters/Player/BP_PlayerMain.uasset
- Content/__ExternalActors__/Levels/House_WP/1/7W/9DT6ZW1N2MSCC9OWGYRYCB.uasset
- Content/__ExternalActors__/Levels/House_WP/1/SL/2XNMOFEX0RM1TR87CG74H7.uasset
- Content/__ExternalActors__/Levels/House_WP/5/K8/Y7BLV0L8KOBMTETMZMEVPK.uasset
- Content/__ExternalActors__/Levels/House_WP/9/9D/Y3HU6GZS4ZWMHK5RC87UA2.uasset
- Content/__ExternalActors__/Levels/House_WP/A/1S/AIR2BXUQ2L1T44W64A2DRH.uasset
- Content/__ExternalActors__/Levels/House_WP/A/DS/H4S8QBW585C4AI8LJR4MOM.uasset
- Content/__ExternalActors__/Levels/House_WP/D/S5/NAF1AM1TE3MG6PQAQHGPQI.uasset
- Content/__ExternalActors__/Levels/House_WP/E/MF/GUCSBLNUA6ZVPCOX1VITVG.uasset
- Source/Eclipse_Rapture/Private/Global/Components/FootstepComponent.cpp
- Source/Eclipse_Rapture/Public/Global/Components/FootstepComponent.h
Began working on the footstep system. Created the actor component and have implemented most logic necessary for this to work.
> Start of footstep system

- Content/Blueprints/Characters/Player/BP_PlayerMain.uasset
- Source/Eclipse_Rapture/Private/Character/EclipseRaptureCharacter.cpp
- Source/Eclipse_Rapture/Public/Character/EclipseRaptureCharacter.h
99% sure that the sprint stamina system is completed. Variables and such are blueprint usable if yall wanna change anything!
> Finished sprint stamina

- Content/Blueprints/Characters/Player/BP_PlayerMain.uasset
- Content/Blueprints/Items/Weapons/Weapons/BP_WeaponBase.uasset
Fixed recoil playing even after the player has run out of ammo in their current weapon.
> recoil fix

- Content/Blueprints/Characters/Player/ABP_EclipseRaptureCharacter.uasset
- Content/Blueprints/Characters/Player/BP_PlayerMain.uasset
- Source/Eclipse_Rapture/Private/Character/EclipseRaptureCharacter.cpp
- Source/Eclipse_Rapture/Public/Character/EclipseRaptureCharacter.h
more work on weapon swapping system
> weapon swapping update

- Source/Eclipse_Rapture/Private/Character/EclipseRaptureCharacter.cpp
Weapon swapping is now (hopefully) completed. No major issues as of now and everything is functional.
> Polished weapon swapping

- Content/Art/3DModels/Weapons/MilitaryWeapDark/Weapons/Assault_Rifle_B.uasset
- Content/Art/3DModels/Weapons/MilitaryWeapSilver/Weapons/Animations/Assault_Rifle_A_Skeleton.uasset
- Content/Art/3DModels/Weapons/MilitaryWeapSilver/Weapons/Pistols_A_Skeleton.uasset
- Content/Art/Animation/PlayerMain(temp)/ADS_Curve.uasset
- Content/Audio/MetaSounds/Stamina/MS_HardBreathing.uasset
- Content/Blueprints/Characters/Player/ABP_EclipseRaptureCharacter.uasset
- Content/Blueprints/Characters/Player/BP_PlayerMain.uasset
- Content/Blueprints/Items/Weapons/Weapons/BP_WeaponBase.uasset
- Content/Levels/AldenTest.umap
- Source/Eclipse_Rapture/Private/Character/EclipseRaptureCharacter.cpp
- Source/Eclipse_Rapture/Public/Character/EclipseRaptureCharacter.h
- Source/Eclipse_Rapture/Public/Weapons/WeaponBase.h
Working on procedural aiming. WIP.
> Procedural aiming

- Content/Blueprints/Characters/Player/ABP_EclipseRaptureCharacter.uasset
- Content/Blueprints/Characters/Player/BP_PlayerMain.uasset
- Source/Eclipse_Rapture/Private/Global/Components/HealthComponent.cpp
- Source/Eclipse_Rapture/Public/Global/Components/HealthComponent.h
Implemented thirst and satiety decreasing code, adjustable in details panel and PIE. Also, fixed player's movement speed not resetting to walk speed after finishing sprinting.
> UI and bugs

- Content/Blueprints/AI/BBD_BaseEnemyAI.uasset
- Content/Blueprints/AI/BTTask_LocateNearbyCoverPoint.uasset
- Content/Blueprints/AI/BTTask_MoveToCover.uasset
- Content/Blueprints/AI/EQ_Cover.uasset
- Content/Blueprints/Items/Weapons/Weapons/BP_WeaponBase.uasset
- Source/Eclipse_Rapture/Private/Building/EclipseRaptureBuildingItem.cpp
- Source/Eclipse_Rapture/Private/Character/EclipseRaptureCharacter.cpp
- Source/Eclipse_Rapture/Private/Interfaces/CoverObject.cpp
- Source/Eclipse_Rapture/Public/Building/EclipseRaptureBuildingItem.h
- Source/Eclipse_Rapture/Public/Enemies/EclipseRaptureEnemy.h
- Source/Eclipse_Rapture/Public/Interfaces/CoverObject.h
- Source/Eclipse_Rapture/Public/Weapons/WeaponBase.h
Enemies should also derive from AEclipseRaptureCharacter starting now.
> Starting to refactor character system

- Content/Blueprints/AI/BBD_BaseEnemyAI.uasset
- Content/Blueprints/UI/Player/BPW_Inventory.uasset
- Source/Eclipse_Rapture/Private/Enemies/EclipseRaptureEnemy.cpp
- Source/Eclipse_Rapture/Public/Enemies/EclipseRaptureEnemy.h
Changed base enemy class parent from EclipseRaptureEnemy to EclipseRaptureCharacter. Removed unnecessary logic that parent already gives.
> Changed base enemy class parent

- Source/Eclipse_Rapture/Private/Character/EclipseRaptureCharacter.cpp
Fixed ranged enemies not attacking
> Fixed ranged enemy attacking

- Content/Levels/WB_AbondonedSchool.umap
Check if your level is still there.
> Created Level map

- Content/Blueprints/AI/AIC_BaseEnemyAI.uasset
- Content/Blueprints/Building/BuildingItems/BP_BaseBuildingItem.uasset
- Content/Blueprints/Building/BuildingItems/BP_TestBuildingItem.uasset
- Content/Blueprints/Characters/Player/BP_EclipseRapturePlayer.uasset
- Content/Blueprints/UI/Player/BPW_PlayerMain.uasset
- Content/Levels/AldenTest.umap
(temp fix- need to go back and figure out why c++ building component isn't working.)
> fixed building

- Content/Blueprints/Building/BuildingItems/BP_BaseBuildingItem.uasset
- Content/Blueprints/Building/BuildingItems/BP_TestBuildingItem.uasset
- Content/Blueprints/Characters/Player/BP_EclipseRapturePlayer.uasset
- Content/Blueprints/Input/IM_EclipseRaptureCharacter.uasset
- Content/Blueprints/Input/KeyboardMouse/IA_BuildMenu.uasset
- Content/Blueprints/UI/Player/BPW_BuildMenu.uasset
- Content/Blueprints/UI/Player/BPW_PlayerMain.uasset
- Source/Eclipse_Rapture/Private/Building/EclipseRaptureBuildingItem.cpp
- Source/Eclipse_Rapture/Private/UI/WidgetBuildMenu.cpp
- Source/Eclipse_Rapture/Public/Building/EclipseRaptureBuildingItem.h
- Source/Eclipse_Rapture/Public/Interfaces/BuildingInterface.h
- Source/Eclipse_Rapture/Public/UI/WidgetBuildMenu.h
Made a temp building ui, will continue to improve this.
> Building UI

- Content/Art/DebugImage.uasset
- Content/Blueprints/Characters/Player/BP_EclipseRapturePlayer.uasset
- Content/Blueprints/UI/Player/BPW_Inventory.uasset
- Content/Blueprints/UI/Player/BPW_InventoryItem.uasset
- Content/Blueprints/UI/Player/BPW_InventoryItemTooltip.uasset
- Source/Eclipse_Rapture/Private/Character/InventoryComponent.cpp
- Source/Eclipse_Rapture/Private/Items/Item.cpp
- Source/Eclipse_Rapture/Private/UI/WidgetInventory.cpp
- Source/Eclipse_Rapture/Private/UI/WidgetInventorySlot.cpp
- Source/Eclipse_Rapture/Private/UI/WidgetItemTooltip.cpp
- Source/Eclipse_Rapture/Public/Character/InventoryComponent.h
- Source/Eclipse_Rapture/Public/Items/Item.h
- Source/Eclipse_Rapture/Public/UI/WidgetInventory.h
- Source/Eclipse_Rapture/Public/UI/WidgetInventorySlot.h
- Source/Eclipse_Rapture/Public/UI/WidgetItemTooltip.h
Reparented inventory widgets to C++ widgets. Changed a lot of logic to start introducing a polished inventory system.
> Inventory Updates

- Content/Blueprints/Characters/Player/BP_EclipseRapturePlayer.uasset
- Content/Blueprints/UI/Player/BPW_Inventory.uasset
- Content/Blueprints/UI/Player/BPW_InventorySlot.uasset
- Source/Eclipse_Rapture/Private/Character/InventoryComponent.cpp
- Source/Eclipse_Rapture/Private/UI/WidgetInventory.cpp
- Source/Eclipse_Rapture/Private/UI/WidgetInventorySlot.cpp
- Source/Eclipse_Rapture/Public/Character/InventoryComponent.h
- Source/Eclipse_Rapture/Public/UI/WidgetInventory.h
- Source/Eclipse_Rapture/Public/UI/WidgetInventorySlot.h
may honestly restart after this one :L
> Inventory work
